// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TMEquipSlotEx","status":true,"description":"アクターごとに部位設定を自由に変更できるようにします。","parameters":{}},
{"name":"TMOmitEquipCommand","status":true,"description":"装備シーンからコマンドウィンドウを削除し、\r\nスロットウィンドウに２行分のスペースを追加します。","parameters":{"useOptimize":"true","useClear":"true"}},
{"name":"TMItemCategoryEx","status":true,"description":"アイテムカテゴリの追加、削除をおこないます。","parameters":{"categoryList":"keyItem"}},
{"name":"InfoWindow","status":true,"description":"情報表示ウィンドウをメニュー画面に追加するプラグイン","parameters":{}},
{"name":"aligncenter","status":true,"description":"メッセージボックスの文字を中央揃い、右揃いにするプラグインです。","parameters":{}}
];
